baseurl                  = "https://sapere-aude.group"           # Your domain name
title                    = "敢于认识"
theme                    = "sam"
hasCJKLanguage = true  # .WordCount works correctly for chinese

[params]
    dateform             = "2006/01/02"
    homepage             = "首页"                           # What to call the home page link

[[params.mainMenu]]
    link = "about"
    text = "愿景"

[[params.mainMenu]]
    link = "read"
    text = "读书"

[[params.mainMenu]]
    link = "member"
    text = "组员"