baseurl        = "https://sapere-aude.group"           # Your domain name
title          = "敢于求知"
theme          = "sam"
hasCJKLanguage = true  # .WordCount works correctly for chinese
disablePathToLower = true

[params]
    dateform   = "2006/01/02"
    homepage   = "首页"                           # What to call the home page link
    githubContentURL   = "https://github.com/Sapere-Aude-Group/sapere-aude/edit/main/content/"

[[params.mainMenu]]
    link = "about"
    text = "愿景"

[[params.mainMenu]]
    link = "read/_introduction/read-tips"
    text = "要求"

[[params.mainMenu]]
    link = "read"
    text = "阅读"

[[params.mainMenu]]
    link = "projects"
    text = "项目"

[[params.mainMenu]]
    link = "member"
    text = "组员"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1